# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43b4c8f140383fb7a0dc6d7857d0ec38784f480cf4c0a546e77555c2bd9f373dccc82af9efa65d52a655874d6bce4b32d529725785d671418cd8ed71e8554390

test:
  secret_key_base: bb78f88beaf207682580872ffaa38281a916b09c03b9352ceaffc61f9237e7d68c3f091b7c981132b830cd4eaf2c098fa3bec4aa7adddcfb06e9a52c921df019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
